formatter: markdown table

recursive:
  enabled: false
  path: .
  include-main: true

sort:
  enabled: true
  by: name

sections:
  hide:
#    - requirements
#    - providers
#    - resources
#    - data-sources
    - modules

output:
  file: README.md
  mode: inject

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 1
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
