name: PR Title

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
      - labeled


permissions:
  contents: read

jobs:
  validate:
    name: Validate PR title
    if: "${{ github.event.pull_request.draft != true && !contains(github.event.pull_request.labels.*.name, 'autorelease: pending') }}"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          configuration_path: ".github/pr-title-checker-config.json"