name: PR Title

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
      - labeled
  # PR title check must be re-run after any Github Action workflow pushes
  # changes to the release branch.
  push:
    branches: [ release-please--branches--master ]


permissions:
  contents: read

jobs:
  validate:
    name: Validate PR title
    if: "${{ github.event.pull_request.draft != true }}"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          configuration_path: ".github/pr-title-checker-config.json"